server:
  port: 8080
  servlet:
    context-path: ""

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: "/h2-console"
  datasource:
    username: sa
    password: as
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver

  flyway:
    url: jdbc:h2:mem:testdb
    user: sa
    password: as
    baseline-on-migrate: true
    baseline-description: "init"
  main:
    allow-circular-references: true

flightsearch:
  jwt:
    security:
      app:
        key: SkRrYL4j4nG6P6SMmwNJBDfRbyrip1BFTOcf8g46sLWd92ytDoyyz3xzyBnaY4csnD1BGLnrmJss8qsPtbL9zPeHkwEx7f1y
      expire:
        time: 86400000

